export const citiesByContinent = {
  'Dominican Republic & Caribbean': [
    'Santo Domingo, Dominican Republic',
    'Santiago, Dominican Republic',
    'Punta Cana, Dominican Republic',
    'San Juan, Puerto Rico',
    'Kingston, Jamaica',
    'Nassau, Bahamas',
    'Port of Spain, Trinidad and Tobago',
  ],
  'Central America': [
    'Panama City, Panama',
    'San José, Costa Rica',
    'Guatemala City, Guatemala',
    'San Salvador, El Salvador',
    'Tegucigalpa, Honduras',
    'Managua, Nicaragua',
    'Belize City, Belize',
  ],
  'North America': [
    'New York, USA',
    'Los Angeles, USA',
    'Chicago, USA',
    'Houston, USA',
    'Miami, USA',
    'Vancouver, Canada',
    'Toronto, Canada',
    'Mexico City, Mexico',
    'Monterrey, Mexico',
  ],
  'South America': [
    'São Paulo, Brazil',
    'Rio de Janeiro, Brazil',
    'Buenos Aires, Argentina',
    'Santiago, Chile',
    'Lima, Peru',
    'Bogotá, Colombia',
    'Caracas, Venezuela',
    'Quito, Ecuador',
    'Asunción, Paraguay',
  ],
  Europe: [
    'London, UK',
    'Amsterdam, Netherlands',
    'Rotterdam, Netherlands',
    'Hamburg, Germany',
    'Frankfurt, Germany',
    'Paris, France',
    'Barcelona, Spain',
    'Madrid, Spain',
    'Lisbon, Portugal',
    'Milan, Italy',
    'Rome, Italy',
    'Istanbul, Turkey',
    'Warsaw, Poland',
    'Prague, Czech Republic',
    'Stockholm, Sweden',
    'Copenhagen, Denmark',
  ],
  Asia: [
    'Shanghai, China',
    'Beijing, China',
    'Shenzhen, China',
    'Hong Kong',
    'Singapore',
    'Tokyo, Japan',
    'Yokohama, Japan',
    'Osaka, Japan',
    'Bangkok, Thailand',
    'Ho Chi Minh City, Vietnam',
    'Hanoi, Vietnam',
    'Manila, Philippines',
    'Jakarta, Indonesia',
    'Surabaya, Indonesia',
    'Kuala Lumpur, Malaysia',
    'Penang, Malaysia',
    'Seoul, South Korea',
    'Busan, South Korea',
    'Mumbai, India',
    'New Delhi, India',
    'Kolkata, India',
    'Chennai, India',
    'Dubai, UAE',
    'Abu Dhabi, UAE',
    'Jeddah, Saudi Arabia',
    'Doha, Qatar',
  ],
  Africa: [
    'Lagos, Nigeria',
    'Cairo, Egypt',
    'Alexandria, Egypt',
    'Johannesburg, South Africa',
    'Cape Town, South Africa',
    'Nairobi, Kenya',
    'Dar es Salaam, Tanzania',
    'Casablanca, Morocco',
    'Dakar, Senegal',
    'Accra, Ghana',
    'Durban, South Africa',
  ],
  Oceania: [
    'Sydney, Australia',
    'Melbourne, Australia',
    'Brisbane, Australia',
    'Perth, Australia',
    'Auckland, New Zealand',
    'Wellington, New Zealand',
    'Singapore',
  ],
}

export const allContinents = Object.keys(citiesByContinent).sort()

export const allCities = Object.values(citiesByContinent).flat().sort()
